//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.BibTeX
{
    
    
    /// <summary>
    /// The default implementation of the BookTitledEntry class
    /// </summary>
    [XmlNamespaceAttribute("http://bibtex/1.0")]
    [XmlNamespacePrefixAttribute("BibTeX")]
    [ModelRepresentationClassAttribute("http://bibtex/1.0#//BookTitledEntry")]
    public abstract partial class BookTitledEntry : BibTeXEntry, IBookTitledEntry, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Booktitle property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _booktitle;
        
        private static Lazy<ITypedElement> _booktitleAttribute = new Lazy<ITypedElement>(RetrieveBooktitleAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The booktitle property
        /// </summary>
        [DisplayNameAttribute("booktitle")]
        [CategoryAttribute("BookTitledEntry")]
        [XmlElementNameAttribute("booktitle")]
        [XmlAttributeAttribute(true)]
        public string Booktitle
        {
            get
            {
                return this._booktitle;
            }
            set
            {
                if ((this._booktitle != value))
                {
                    string old = this._booktitle;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnBooktitleChanging(e);
                    this.OnPropertyChanging("Booktitle", e, _booktitleAttribute);
                    this._booktitle = value;
                    this.OnBooktitleChanged(e);
                    this.OnPropertyChanged("Booktitle", e, _booktitleAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://bibtex/1.0#//BookTitledEntry")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Booktitle property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> BooktitleChanging;
        
        /// <summary>
        /// Gets fired when the Booktitle property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> BooktitleChanged;
        
        private static ITypedElement RetrieveBooktitleAttribute()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.BibTeX.BookTitledEntry.ClassInstance)).Resolve("booktitle")));
        }
        
        /// <summary>
        /// Raises the BooktitleChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnBooktitleChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.BooktitleChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the BooktitleChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnBooktitleChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.BooktitleChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "BOOKTITLE"))
            {
                return this.Booktitle;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "BOOKTITLE"))
            {
                this.Booktitle = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "BOOKTITLE"))
            {
                return new BooktitleProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://bibtex/1.0#//BookTitledEntry")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the booktitle property
        /// </summary>
        private sealed class BooktitleProxy : ModelPropertyChange<IBookTitledEntry, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public BooktitleProxy(IBookTitledEntry modelElement) : 
                    base(modelElement, "booktitle")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Booktitle;
                }
                set
                {
                    this.ModelElement.Booktitle = value;
                }
            }
        }
    }
}

