//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.PetriNet
{
    
    
    /// <summary>
    /// The public interface for TransitionToPlace
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(TransitionToPlace))]
    [XmlDefaultImplementationTypeAttribute(typeof(TransitionToPlace))]
    [ModelRepresentationClassAttribute("http://petrinet/1.0#//TransitionToPlace")]
    public interface ITransitionToPlace : IModelElement, IArc
    {
        
        /// <summary>
        /// The from property
        /// </summary>
        [DisplayNameAttribute("from")]
        [CategoryAttribute("TransitionToPlace")]
        [XmlElementNameAttribute("from")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("outgoingArc")]
        ITransition From
        {
            get;
            set;
        }
        
        /// <summary>
        /// The to property
        /// </summary>
        [DisplayNameAttribute("to")]
        [CategoryAttribute("TransitionToPlace")]
        [XmlElementNameAttribute("to")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("incomingArc")]
        IPlace To
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the From property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FromChanging;
        
        /// <summary>
        /// Gets fired when the From property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FromChanged;
        
        /// <summary>
        /// Gets fired before the To property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ToChanging;
        
        /// <summary>
        /// Gets fired when the To property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ToChanged;
    }
}

