//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.CPL
{
    
    
    /// <summary>
    /// The public interface for Reject
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Reject))]
    [XmlDefaultImplementationTypeAttribute(typeof(Reject))]
    [ModelRepresentationClassAttribute("http://cpl/1.0#//Reject")]
    public interface IReject : IModelElement, ISignallingAction
    {
        
        /// <summary>
        /// The status property
        /// </summary>
        [DisplayNameAttribute("status")]
        [CategoryAttribute("Reject")]
        [XmlElementNameAttribute("status")]
        [XmlAttributeAttribute(true)]
        string Status
        {
            get;
            set;
        }
        
        /// <summary>
        /// The reason property
        /// </summary>
        [DisplayNameAttribute("reason")]
        [CategoryAttribute("Reject")]
        [XmlElementNameAttribute("reason")]
        [XmlAttributeAttribute(true)]
        string Reason
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Status property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> StatusChanging;
        
        /// <summary>
        /// Gets fired when the Status property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> StatusChanged;
        
        /// <summary>
        /// Gets fired before the Reason property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ReasonChanging;
        
        /// <summary>
        /// Gets fired when the Reason property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ReasonChanged;
    }
}

