//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.CPL
{
    
    
    /// <summary>
    /// The public interface for StringSwitch
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(StringSwitch))]
    [XmlDefaultImplementationTypeAttribute(typeof(StringSwitch))]
    [ModelRepresentationClassAttribute("http://cpl/1.0#//StringSwitch")]
    public interface IStringSwitch : IModelElement, ISwitch
    {
        
        /// <summary>
        /// The field property
        /// </summary>
        [DisplayNameAttribute("field")]
        [CategoryAttribute("StringSwitch")]
        [XmlElementNameAttribute("field")]
        [XmlAttributeAttribute(true)]
        string Field
        {
            get;
            set;
        }
        
        /// <summary>
        /// The strings property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("strings")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IOrderedSetExpression<ISwitchedString> Strings
        {
            get;
        }
        
        /// <summary>
        /// Gets fired before the Field property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FieldChanging;
        
        /// <summary>
        /// Gets fired when the Field property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FieldChanged;
    }
}

