//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.CPL
{
    
    
    /// <summary>
    /// The public interface for SwitchedPriority
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(SwitchedPriority))]
    [XmlDefaultImplementationTypeAttribute(typeof(SwitchedPriority))]
    [ModelRepresentationClassAttribute("http://cpl/1.0#//SwitchedPriority")]
    public interface ISwitchedPriority : IModelElement, INodeContainer
    {
        
        /// <summary>
        /// The less property
        /// </summary>
        [DisplayNameAttribute("less")]
        [CategoryAttribute("SwitchedPriority")]
        [XmlElementNameAttribute("less")]
        [XmlAttributeAttribute(true)]
        string Less
        {
            get;
            set;
        }
        
        /// <summary>
        /// The greater property
        /// </summary>
        [DisplayNameAttribute("greater")]
        [CategoryAttribute("SwitchedPriority")]
        [XmlElementNameAttribute("greater")]
        [XmlAttributeAttribute(true)]
        string Greater
        {
            get;
            set;
        }
        
        /// <summary>
        /// The equal property
        /// </summary>
        [DisplayNameAttribute("equal")]
        [CategoryAttribute("SwitchedPriority")]
        [XmlElementNameAttribute("equal")]
        [XmlAttributeAttribute(true)]
        string Equal
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Less property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LessChanging;
        
        /// <summary>
        /// Gets fired when the Less property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LessChanged;
        
        /// <summary>
        /// Gets fired before the Greater property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> GreaterChanging;
        
        /// <summary>
        /// Gets fired when the Greater property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> GreaterChanged;
        
        /// <summary>
        /// Gets fired before the Equal property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EqualChanging;
        
        /// <summary>
        /// Gets fired when the Equal property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EqualChanged;
    }
}

