//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.CPL
{
    
    
    /// <summary>
    /// The public interface for Switch
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Switch))]
    [XmlDefaultImplementationTypeAttribute(typeof(Switch))]
    [ModelRepresentationClassAttribute("http://cpl/1.0#//Switch")]
    public interface ISwitch : IModelElement, INode
    {
        
        /// <summary>
        /// The notPresent property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("notPresent")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        INotPresent NotPresent
        {
            get;
            set;
        }
        
        /// <summary>
        /// The otherwise property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("otherwise")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        IOtherwise Otherwise
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the NotPresent property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NotPresentChanging;
        
        /// <summary>
        /// Gets fired when the NotPresent property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NotPresentChanged;
        
        /// <summary>
        /// Gets fired before the Otherwise property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OtherwiseChanging;
        
        /// <summary>
        /// Gets fired when the Otherwise property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OtherwiseChanged;
    }
}

