//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.CPL
{
    
    
    /// <summary>
    /// The default implementation of the Location class
    /// </summary>
    [XmlNamespaceAttribute("http://cpl/1.0")]
    [XmlNamespacePrefixAttribute("CPL")]
    [ModelRepresentationClassAttribute("http://cpl/1.0#//Location")]
    public partial class Location : Node, ILocation, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Url property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _url;
        
        private static Lazy<ITypedElement> _urlAttribute = new Lazy<ITypedElement>(RetrieveUrlAttribute);
        
        /// <summary>
        /// The backing field for the Priority property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _priority;
        
        private static Lazy<ITypedElement> _priorityAttribute = new Lazy<ITypedElement>(RetrievePriorityAttribute);
        
        /// <summary>
        /// The backing field for the Clear property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _clear;
        
        private static Lazy<ITypedElement> _clearAttribute = new Lazy<ITypedElement>(RetrieveClearAttribute);
        
        private static Lazy<ITypedElement> _contentsReference = new Lazy<ITypedElement>(RetrieveContentsReference);
        
        /// <summary>
        /// The backing field for the Contents property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private INode _contents;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The url property
        /// </summary>
        [DisplayNameAttribute("url")]
        [CategoryAttribute("Location")]
        [XmlElementNameAttribute("url")]
        [XmlAttributeAttribute(true)]
        public string Url
        {
            get
            {
                return this._url;
            }
            set
            {
                if ((this._url != value))
                {
                    string old = this._url;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnUrlChanging(e);
                    this.OnPropertyChanging("Url", e, _urlAttribute);
                    this._url = value;
                    this.OnUrlChanged(e);
                    this.OnPropertyChanged("Url", e, _urlAttribute);
                }
            }
        }
        
        /// <summary>
        /// The priority property
        /// </summary>
        [DisplayNameAttribute("priority")]
        [CategoryAttribute("Location")]
        [XmlElementNameAttribute("priority")]
        [XmlAttributeAttribute(true)]
        public string Priority
        {
            get
            {
                return this._priority;
            }
            set
            {
                if ((this._priority != value))
                {
                    string old = this._priority;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnPriorityChanging(e);
                    this.OnPropertyChanging("Priority", e, _priorityAttribute);
                    this._priority = value;
                    this.OnPriorityChanged(e);
                    this.OnPropertyChanged("Priority", e, _priorityAttribute);
                }
            }
        }
        
        /// <summary>
        /// The clear property
        /// </summary>
        [DisplayNameAttribute("clear")]
        [CategoryAttribute("Location")]
        [XmlElementNameAttribute("clear")]
        [XmlAttributeAttribute(true)]
        public string Clear
        {
            get
            {
                return this._clear;
            }
            set
            {
                if ((this._clear != value))
                {
                    string old = this._clear;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnClearChanging(e);
                    this.OnPropertyChanging("Clear", e, _clearAttribute);
                    this._clear = value;
                    this.OnClearChanged(e);
                    this.OnPropertyChanged("Clear", e, _clearAttribute);
                }
            }
        }
        
        /// <summary>
        /// The contents property
        /// </summary>
        [DisplayNameAttribute("contents")]
        [CategoryAttribute("NodeContainer")]
        [XmlElementNameAttribute("contents")]
        [XmlAttributeAttribute(true)]
        public INode Contents
        {
            get
            {
                return this._contents;
            }
            set
            {
                if ((this._contents != value))
                {
                    INode old = this._contents;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnContentsChanging(e);
                    this.OnPropertyChanging("Contents", e, _contentsReference);
                    this._contents = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetContents;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetContents;
                    }
                    this.OnContentsChanged(e);
                    this.OnPropertyChanged("Contents", e, _contentsReference);
                }
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new LocationChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://cpl/1.0#//Location")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Url property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> UrlChanging;
        
        /// <summary>
        /// Gets fired when the Url property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> UrlChanged;
        
        /// <summary>
        /// Gets fired before the Priority property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> PriorityChanging;
        
        /// <summary>
        /// Gets fired when the Priority property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> PriorityChanged;
        
        /// <summary>
        /// Gets fired before the Clear property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ClearChanging;
        
        /// <summary>
        /// Gets fired when the Clear property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ClearChanged;
        
        /// <summary>
        /// Gets fired before the Contents property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ContentsChanging;
        
        /// <summary>
        /// Gets fired when the Contents property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ContentsChanged;
        
        private static ITypedElement RetrieveUrlAttribute()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.CPL.Location.ClassInstance)).Resolve("url")));
        }
        
        /// <summary>
        /// Raises the UrlChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnUrlChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.UrlChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the UrlChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnUrlChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.UrlChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrievePriorityAttribute()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.CPL.Location.ClassInstance)).Resolve("priority")));
        }
        
        /// <summary>
        /// Raises the PriorityChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnPriorityChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.PriorityChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the PriorityChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnPriorityChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.PriorityChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveClearAttribute()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.CPL.Location.ClassInstance)).Resolve("clear")));
        }
        
        /// <summary>
        /// Raises the ClearChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnClearChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ClearChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the ClearChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnClearChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ClearChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveContentsReference()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.CPL.NodeContainer.ClassInstance)).Resolve("contents")));
        }
        
        /// <summary>
        /// Raises the ContentsChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnContentsChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ContentsChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the ContentsChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnContentsChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ContentsChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Contents property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetContents(object sender, System.EventArgs eventArgs)
        {
            this.Contents = null;
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "CONTENTS"))
            {
                return this.Contents;
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "URL"))
            {
                return this.Url;
            }
            if ((attribute == "PRIORITY"))
            {
                return this.Priority;
            }
            if ((attribute == "CLEAR"))
            {
                return this.Clear;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "CONTENTS"))
            {
                this.Contents = ((INode)(value));
                return;
            }
            if ((feature == "URL"))
            {
                this.Url = ((string)(value));
                return;
            }
            if ((feature == "PRIORITY"))
            {
                this.Priority = ((string)(value));
                return;
            }
            if ((feature == "CLEAR"))
            {
                this.Clear = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "URL"))
            {
                return new UrlProxy(this);
            }
            if ((attribute == "PRIORITY"))
            {
                return new PriorityProxy(this);
            }
            if ((attribute == "CLEAR"))
            {
                return new ClearProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "CONTENTS"))
            {
                return new ContentsProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://cpl/1.0#//Location")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Location class
        /// </summary>
        public class LocationChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Location _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public LocationChildrenCollection(Location parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
            }
            
            protected override void DetachCore()
            {
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the url property
        /// </summary>
        private sealed class UrlProxy : ModelPropertyChange<ILocation, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public UrlProxy(ILocation modelElement) : 
                    base(modelElement, "url")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Url;
                }
                set
                {
                    this.ModelElement.Url = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the priority property
        /// </summary>
        private sealed class PriorityProxy : ModelPropertyChange<ILocation, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public PriorityProxy(ILocation modelElement) : 
                    base(modelElement, "priority")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Priority;
                }
                set
                {
                    this.ModelElement.Priority = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the clear property
        /// </summary>
        private sealed class ClearProxy : ModelPropertyChange<ILocation, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public ClearProxy(ILocation modelElement) : 
                    base(modelElement, "clear")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Clear;
                }
                set
                {
                    this.ModelElement.Clear = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the contents property
        /// </summary>
        private sealed class ContentsProxy : ModelPropertyChange<INodeContainer, INode>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public ContentsProxy(INodeContainer modelElement) : 
                    base(modelElement, "contents")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override INode Value
            {
                get
                {
                    return this.ModelElement.Contents;
                }
                set
                {
                    this.ModelElement.Contents = value;
                }
            }
        }
    }
}

