//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.CPL
{
    
    
    /// <summary>
    /// The default implementation of the SwitchedLanguage class
    /// </summary>
    [XmlNamespaceAttribute("http://cpl/1.0")]
    [XmlNamespacePrefixAttribute("CPL")]
    [ModelRepresentationClassAttribute("http://cpl/1.0#//SwitchedLanguage")]
    public partial class SwitchedLanguage : NodeContainer, ISwitchedLanguage, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Matches property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _matches;
        
        private static Lazy<ITypedElement> _matchesAttribute = new Lazy<ITypedElement>(RetrieveMatchesAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The matches property
        /// </summary>
        [DisplayNameAttribute("matches")]
        [CategoryAttribute("SwitchedLanguage")]
        [XmlElementNameAttribute("matches")]
        [XmlAttributeAttribute(true)]
        public string Matches
        {
            get
            {
                return this._matches;
            }
            set
            {
                if ((this._matches != value))
                {
                    string old = this._matches;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnMatchesChanging(e);
                    this.OnPropertyChanging("Matches", e, _matchesAttribute);
                    this._matches = value;
                    this.OnMatchesChanged(e);
                    this.OnPropertyChanged("Matches", e, _matchesAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://cpl/1.0#//SwitchedLanguage")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Matches property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> MatchesChanging;
        
        /// <summary>
        /// Gets fired when the Matches property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> MatchesChanged;
        
        private static ITypedElement RetrieveMatchesAttribute()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.CPL.SwitchedLanguage.ClassInstance)).Resolve("matches")));
        }
        
        /// <summary>
        /// Raises the MatchesChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnMatchesChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.MatchesChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the MatchesChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnMatchesChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.MatchesChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "MATCHES"))
            {
                return this.Matches;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "MATCHES"))
            {
                this.Matches = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "MATCHES"))
            {
                return new MatchesProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://cpl/1.0#//SwitchedLanguage")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the matches property
        /// </summary>
        private sealed class MatchesProxy : ModelPropertyChange<ISwitchedLanguage, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public MatchesProxy(ISwitchedLanguage modelElement) : 
                    base(modelElement, "matches")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Matches;
                }
                set
                {
                    this.ModelElement.Matches = value;
                }
            }
        }
    }
}

