//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.Hsm
{
    
    
    /// <summary>
    /// The default implementation of the AbstractState class
    /// </summary>
    [XmlIdentifierAttribute("name")]
    [XmlNamespaceAttribute("http://hsm/1.0")]
    [XmlNamespacePrefixAttribute("hsm")]
    [ModelRepresentationClassAttribute("http://hsm/1.0#//AbstractState")]
    [DebuggerDisplayAttribute("AbstractState {Name}")]
    public abstract partial class AbstractState : ModelElement, IAbstractState, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Name property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _name;
        
        private static Lazy<ITypedElement> _nameAttribute = new Lazy<ITypedElement>(RetrieveNameAttribute);
        
        private static Lazy<ITypedElement> _stateMachineReference = new Lazy<ITypedElement>(RetrieveStateMachineReference);
        
        private static Lazy<ITypedElement> _compositeStatesReference = new Lazy<ITypedElement>(RetrieveCompositeStatesReference);
        
        /// <summary>
        /// The backing field for the CompositeStates property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ICompositeState _compositeStates;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The name property
        /// </summary>
        [DisplayNameAttribute("name")]
        [CategoryAttribute("AbstractState")]
        [XmlElementNameAttribute("name")]
        [IdAttribute()]
        [XmlAttributeAttribute(true)]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    string old = this._name;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnNameChanging(e);
                    this.OnPropertyChanging("Name", e, _nameAttribute);
                    this._name = value;
                    this.OnNameChanged(e);
                    this.OnPropertyChanged("Name", e, _nameAttribute);
                }
            }
        }
        
        /// <summary>
        /// The stateMachine property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("stateMachine")]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("states")]
        public IStateMachine StateMachine
        {
            get
            {
                return ModelHelper.CastAs<IStateMachine>(this.Parent);
            }
            set
            {
                this.Parent = value;
            }
        }
        
        /// <summary>
        /// The compositeStates property
        /// </summary>
        [DisplayNameAttribute("compositeStates")]
        [CategoryAttribute("AbstractState")]
        [XmlElementNameAttribute("compositeStates")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("states")]
        public ICompositeState CompositeStates
        {
            get
            {
                return this._compositeStates;
            }
            set
            {
                if ((this._compositeStates != value))
                {
                    ICompositeState old = this._compositeStates;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnCompositeStatesChanging(e);
                    this.OnPropertyChanging("CompositeStates", e, _compositeStatesReference);
                    this._compositeStates = value;
                    if ((old != null))
                    {
                        old.States.Remove(this);
                        old.Deleted -= this.OnResetCompositeStates;
                    }
                    if ((value != null))
                    {
                        value.States.Add(this);
                        value.Deleted += this.OnResetCompositeStates;
                    }
                    this.OnCompositeStatesChanged(e);
                    this.OnPropertyChanged("CompositeStates", e, _compositeStatesReference);
                }
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new AbstractStateReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://hsm/1.0#//AbstractState")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets a value indicating whether the current model element can be identified by an attribute value
        /// </summary>
        public override bool IsIdentified
        {
            get
            {
                return true;
            }
        }
        
        /// <summary>
        /// Gets fired before the Name property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> NameChanging;
        
        /// <summary>
        /// Gets fired when the Name property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> NameChanged;
        
        /// <summary>
        /// Gets fired before the StateMachine property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> StateMachineChanging;
        
        /// <summary>
        /// Gets fired when the StateMachine property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> StateMachineChanged;
        
        /// <summary>
        /// Gets fired before the CompositeStates property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> CompositeStatesChanging;
        
        /// <summary>
        /// Gets fired when the CompositeStates property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> CompositeStatesChanged;
        
        private static ITypedElement RetrieveNameAttribute()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.Hsm.AbstractState.ClassInstance)).Resolve("name")));
        }
        
        /// <summary>
        /// Raises the NameChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnNameChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.NameChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the NameChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnNameChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.NameChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveStateMachineReference()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.Hsm.AbstractState.ClassInstance)).Resolve("stateMachine")));
        }
        
        /// <summary>
        /// Raises the StateMachineChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnStateMachineChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.StateMachineChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Gets called when the parent model element of the current model element is about to change
        /// </summary>
        /// <param name="oldParent">The old parent model element</param>
        /// <param name="newParent">The new parent model element</param>
        protected override void OnParentChanging(IModelElement newParent, IModelElement oldParent)
        {
            IStateMachine oldStateMachine = ModelHelper.CastAs<IStateMachine>(oldParent);
            IStateMachine newStateMachine = ModelHelper.CastAs<IStateMachine>(newParent);
            ValueChangedEventArgs e = new ValueChangedEventArgs(oldStateMachine, newStateMachine);
            this.OnStateMachineChanging(e);
            this.OnPropertyChanging("StateMachine", e, _stateMachineReference);
        }
        
        /// <summary>
        /// Raises the StateMachineChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnStateMachineChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.StateMachineChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Gets called when the parent model element of the current model element changes
        /// </summary>
        /// <param name="oldParent">The old parent model element</param>
        /// <param name="newParent">The new parent model element</param>
        protected override void OnParentChanged(IModelElement newParent, IModelElement oldParent)
        {
            IStateMachine oldStateMachine = ModelHelper.CastAs<IStateMachine>(oldParent);
            IStateMachine newStateMachine = ModelHelper.CastAs<IStateMachine>(newParent);
            if ((oldStateMachine != null))
            {
                oldStateMachine.States.Remove(this);
            }
            if ((newStateMachine != null))
            {
                newStateMachine.States.Add(this);
            }
            ValueChangedEventArgs e = new ValueChangedEventArgs(oldStateMachine, newStateMachine);
            this.OnStateMachineChanged(e);
            this.OnPropertyChanged("StateMachine", e, _stateMachineReference);
            base.OnParentChanged(newParent, oldParent);
        }
        
        private static ITypedElement RetrieveCompositeStatesReference()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.Hsm.AbstractState.ClassInstance)).Resolve("compositeStates")));
        }
        
        /// <summary>
        /// Raises the CompositeStatesChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnCompositeStatesChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.CompositeStatesChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the CompositeStatesChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnCompositeStatesChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.CompositeStatesChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the CompositeStates property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetCompositeStates(object sender, System.EventArgs eventArgs)
        {
            this.CompositeStates = null;
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "STATEMACHINE"))
            {
                return this.StateMachine;
            }
            if ((reference == "COMPOSITESTATES"))
            {
                return this.CompositeStates;
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "NAME"))
            {
                return this.Name;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "STATEMACHINE"))
            {
                this.StateMachine = ((IStateMachine)(value));
                return;
            }
            if ((feature == "COMPOSITESTATES"))
            {
                this.CompositeStates = ((ICompositeState)(value));
                return;
            }
            if ((feature == "NAME"))
            {
                this.Name = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "NAME"))
            {
                return new NameProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "STATEMACHINE"))
            {
                return new StateMachineProxy(this);
            }
            if ((reference == "COMPOSITESTATES"))
            {
                return new CompositeStatesProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://hsm/1.0#//AbstractState")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Gets the identifier string for this model element
        /// </summary>
        /// <returns>The identifier string</returns>
        public override string ToIdentifierString()
        {
            if ((this.Name == null))
            {
                return null;
            }
            return this.Name.ToString();
        }
        
        /// <summary>
        /// The collection class to to represent the children of the AbstractState class
        /// </summary>
        public class AbstractStateReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private AbstractState _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public AbstractStateReferencedElementsCollection(AbstractState parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.StateMachine != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.CompositeStates != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.StateMachineChanged += this.PropagateValueChanges;
                this._parent.CompositeStatesChanged += this.PropagateValueChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.StateMachineChanged -= this.PropagateValueChanges;
                this._parent.CompositeStatesChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.StateMachine == null))
                {
                    IStateMachine stateMachineCasted = item.As<IStateMachine>();
                    if ((stateMachineCasted != null))
                    {
                        this._parent.StateMachine = stateMachineCasted;
                        return;
                    }
                }
                if ((this._parent.CompositeStates == null))
                {
                    ICompositeState compositeStatesCasted = item.As<ICompositeState>();
                    if ((compositeStatesCasted != null))
                    {
                        this._parent.CompositeStates = compositeStatesCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.StateMachine = null;
                this._parent.CompositeStates = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.StateMachine))
                {
                    return true;
                }
                if ((item == this._parent.CompositeStates))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.StateMachine != null))
                {
                    array[arrayIndex] = this._parent.StateMachine;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.CompositeStates != null))
                {
                    array[arrayIndex] = this._parent.CompositeStates;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.StateMachine == item))
                {
                    this._parent.StateMachine = null;
                    return true;
                }
                if ((this._parent.CompositeStates == item))
                {
                    this._parent.CompositeStates = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.StateMachine).Concat(this._parent.CompositeStates).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the name property
        /// </summary>
        private sealed class NameProxy : ModelPropertyChange<IAbstractState, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public NameProxy(IAbstractState modelElement) : 
                    base(modelElement, "name")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Name;
                }
                set
                {
                    this.ModelElement.Name = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the stateMachine property
        /// </summary>
        private sealed class StateMachineProxy : ModelPropertyChange<IAbstractState, IStateMachine>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public StateMachineProxy(IAbstractState modelElement) : 
                    base(modelElement, "stateMachine")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IStateMachine Value
            {
                get
                {
                    return this.ModelElement.StateMachine;
                }
                set
                {
                    this.ModelElement.StateMachine = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the compositeStates property
        /// </summary>
        private sealed class CompositeStatesProxy : ModelPropertyChange<IAbstractState, ICompositeState>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public CompositeStatesProxy(IAbstractState modelElement) : 
                    base(modelElement, "compositeStates")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override ICompositeState Value
            {
                get
                {
                    return this.ModelElement.CompositeStates;
                }
                set
                {
                    this.ModelElement.CompositeStates = value;
                }
            }
        }
    }
}

