//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.ArchitectureCRA
{
    
    
    /// <summary>
    /// The default implementation of the ClassModel class
    /// </summary>
    [XmlNamespaceAttribute("http://momot.big.tuwien.ac.at/architectureCRA/1.0")]
    [XmlNamespacePrefixAttribute("architectureCRA")]
    [ModelRepresentationClassAttribute("http://momot.big.tuwien.ac.at/architectureCRA/1.0#//ClassModel")]
    [DebuggerDisplayAttribute("ClassModel {Name}")]
    public partial class ClassModel : NamedElement, IClassModel, IModelElement
    {
        
        private static Lazy<ITypedElement> _classesReference = new Lazy<ITypedElement>(RetrieveClassesReference);
        
        /// <summary>
        /// The backing field for the Classes property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ObservableCompositionOrderedSet<MDEMGTT.ArchitectureCRA.IClass> _classes;
        
        private static Lazy<ITypedElement> _featuresReference = new Lazy<ITypedElement>(RetrieveFeaturesReference);
        
        /// <summary>
        /// The backing field for the Features property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ObservableCompositionOrderedSet<IFeature> _features;
        
        private static NMF.Models.Meta.IClass _classInstance;
        
        public ClassModel()
        {
            this._classes = new ObservableCompositionOrderedSet<MDEMGTT.ArchitectureCRA.IClass>(this);
            this._classes.CollectionChanging += this.ClassesCollectionChanging;
            this._classes.CollectionChanged += this.ClassesCollectionChanged;
            this._features = new ObservableCompositionOrderedSet<IFeature>(this);
            this._features.CollectionChanging += this.FeaturesCollectionChanging;
            this._features.CollectionChanged += this.FeaturesCollectionChanged;
        }
        
        /// <summary>
        /// The classes property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("classes")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public IOrderedSetExpression<MDEMGTT.ArchitectureCRA.IClass> Classes
        {
            get
            {
                return this._classes;
            }
        }
        
        /// <summary>
        /// The features property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("features")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public IOrderedSetExpression<IFeature> Features
        {
            get
            {
                return this._features;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new ClassModelChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new ClassModelReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static NMF.Models.Meta.IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("http://momot.big.tuwien.ac.at/architectureCRA/1.0#//ClassModel")));
                }
                return _classInstance;
            }
        }
        
        private static ITypedElement RetrieveClassesReference()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.ArchitectureCRA.ClassModel.ClassInstance)).Resolve("classes")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Classes property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ClassesCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Classes", e, _classesReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Classes property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ClassesCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Classes", e, _classesReference);
        }
        
        private static ITypedElement RetrieveFeaturesReference()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.ArchitectureCRA.ClassModel.ClassInstance)).Resolve("features")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Features property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void FeaturesCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Features", e, _featuresReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Features property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void FeaturesCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Features", e, _featuresReference);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int classesIndex = ModelHelper.IndexOfReference(this.Classes, element);
            if ((classesIndex != -1))
            {
                return ModelHelper.CreatePath("classes", classesIndex);
            }
            int featuresIndex = ModelHelper.IndexOfReference(this.Features, element);
            if ((featuresIndex != -1))
            {
                return ModelHelper.CreatePath("features", featuresIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "CLASSES"))
            {
                if ((index < this.Classes.Count))
                {
                    return this.Classes[index];
                }
                else
                {
                    return null;
                }
            }
            if ((reference == "FEATURES"))
            {
                if ((index < this.Features.Count))
                {
                    return this.Features[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "CLASSES"))
            {
                return this._classes;
            }
            if ((feature == "FEATURES"))
            {
                return this._features;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this._classes))
            {
                return "classes";
            }
            if ((container == this._features))
            {
                return "features";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override NMF.Models.Meta.IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("http://momot.big.tuwien.ac.at/architectureCRA/1.0#//ClassModel")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the ClassModel class
        /// </summary>
        public class ClassModelChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private ClassModel _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ClassModelChildrenCollection(ClassModel parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Classes.Count);
                    count = (count + this._parent.Features.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Classes.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Features.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Classes.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Features.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                MDEMGTT.ArchitectureCRA.IClass classesCasted = item.As<MDEMGTT.ArchitectureCRA.IClass>();
                if ((classesCasted != null))
                {
                    this._parent.Classes.Add(classesCasted);
                }
                IFeature featuresCasted = item.As<IFeature>();
                if ((featuresCasted != null))
                {
                    this._parent.Features.Add(featuresCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Classes.Clear();
                this._parent.Features.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Classes.Contains(item))
                {
                    return true;
                }
                if (this._parent.Features.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> classesEnumerator = this._parent.Classes.GetEnumerator();
                try
                {
                    for (
                    ; classesEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = classesEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    classesEnumerator.Dispose();
                }
                IEnumerator<IModelElement> featuresEnumerator = this._parent.Features.GetEnumerator();
                try
                {
                    for (
                    ; featuresEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = featuresEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    featuresEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                MDEMGTT.ArchitectureCRA.IClass classItem = item.As<MDEMGTT.ArchitectureCRA.IClass>();
                if (((classItem != null) 
                            && this._parent.Classes.Remove(classItem)))
                {
                    return true;
                }
                IFeature featureItem = item.As<IFeature>();
                if (((featureItem != null) 
                            && this._parent.Features.Remove(featureItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Classes).Concat(this._parent.Features).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the ClassModel class
        /// </summary>
        public class ClassModelReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private ClassModel _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ClassModelReferencedElementsCollection(ClassModel parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Classes.Count);
                    count = (count + this._parent.Features.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Classes.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Features.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Classes.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Features.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                MDEMGTT.ArchitectureCRA.IClass classesCasted = item.As<MDEMGTT.ArchitectureCRA.IClass>();
                if ((classesCasted != null))
                {
                    this._parent.Classes.Add(classesCasted);
                }
                IFeature featuresCasted = item.As<IFeature>();
                if ((featuresCasted != null))
                {
                    this._parent.Features.Add(featuresCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Classes.Clear();
                this._parent.Features.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Classes.Contains(item))
                {
                    return true;
                }
                if (this._parent.Features.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> classesEnumerator = this._parent.Classes.GetEnumerator();
                try
                {
                    for (
                    ; classesEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = classesEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    classesEnumerator.Dispose();
                }
                IEnumerator<IModelElement> featuresEnumerator = this._parent.Features.GetEnumerator();
                try
                {
                    for (
                    ; featuresEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = featuresEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    featuresEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                MDEMGTT.ArchitectureCRA.IClass classItem = item.As<MDEMGTT.ArchitectureCRA.IClass>();
                if (((classItem != null) 
                            && this._parent.Classes.Remove(classItem)))
                {
                    return true;
                }
                IFeature featureItem = item.As<IFeature>();
                if (((featureItem != null) 
                            && this._parent.Features.Remove(featureItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Classes).Concat(this._parent.Features).GetEnumerator();
            }
        }
    }
}

