//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.PetriNet
{
    
    
    /// <summary>
    /// The public interface for Arc
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Arc))]
    [XmlDefaultImplementationTypeAttribute(typeof(Arc))]
    [ModelRepresentationClassAttribute("http://petrinet/1.0#//Arc")]
    public interface IArc : IModelElement, INamedElement
    {
        
        /// <summary>
        /// The weight property
        /// </summary>
        [DisplayNameAttribute("weight")]
        [CategoryAttribute("Arc")]
        [XmlElementNameAttribute("weight")]
        [XmlAttributeAttribute(true)]
        int Weight
        {
            get;
            set;
        }
        
        /// <summary>
        /// The net property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("net")]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("arcs")]
        IPetriNet Net
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Weight property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WeightChanging;
        
        /// <summary>
        /// Gets fired when the Weight property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WeightChanged;
        
        /// <summary>
        /// Gets fired before the Net property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NetChanging;
        
        /// <summary>
        /// Gets fired when the Net property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NetChanged;
    }
}

