//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace MDEMGTT.PetriNet
{
    
    
    /// <summary>
    /// The default implementation of the PetriNet class
    /// </summary>
    [XmlNamespaceAttribute("http://petrinet/1.0")]
    [XmlNamespacePrefixAttribute("petriNet")]
    [ModelRepresentationClassAttribute("http://petrinet/1.0#//PetriNet")]
    [DebuggerDisplayAttribute("PetriNet {Name}")]
    public partial class PetriNet : NamedElement, IPetriNet, IModelElement
    {
        
        private static Lazy<ITypedElement> _elementsReference = new Lazy<ITypedElement>(RetrieveElementsReference);
        
        /// <summary>
        /// The backing field for the Elements property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private PetriNetElementsCollection _elements;
        
        private static Lazy<ITypedElement> _arcsReference = new Lazy<ITypedElement>(RetrieveArcsReference);
        
        /// <summary>
        /// The backing field for the Arcs property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private PetriNetArcsCollection _arcs;
        
        private static IClass _classInstance;
        
        public PetriNet()
        {
            this._elements = new PetriNetElementsCollection(this);
            this._elements.CollectionChanging += this.ElementsCollectionChanging;
            this._elements.CollectionChanged += this.ElementsCollectionChanged;
            this._arcs = new PetriNetArcsCollection(this);
            this._arcs.CollectionChanging += this.ArcsCollectionChanging;
            this._arcs.CollectionChanged += this.ArcsCollectionChanged;
        }
        
        /// <summary>
        /// The elements property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("elements")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("net")]
        [ConstantAttribute()]
        public IOrderedSetExpression<IElement> Elements
        {
            get
            {
                return this._elements;
            }
        }
        
        /// <summary>
        /// The arcs property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("arcs")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("net")]
        [ConstantAttribute()]
        public IOrderedSetExpression<IArc> Arcs
        {
            get
            {
                return this._arcs;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new PetriNetChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new PetriNetReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://petrinet/1.0#//PetriNet")));
                }
                return _classInstance;
            }
        }
        
        private static ITypedElement RetrieveElementsReference()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.PetriNet.PetriNet.ClassInstance)).Resolve("elements")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Elements property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ElementsCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Elements", e, _elementsReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Elements property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ElementsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Elements", e, _elementsReference);
        }
        
        private static ITypedElement RetrieveArcsReference()
        {
            return ((ITypedElement)(((ModelElement)(MDEMGTT.PetriNet.PetriNet.ClassInstance)).Resolve("arcs")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Arcs property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ArcsCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Arcs", e, _arcsReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Arcs property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ArcsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Arcs", e, _arcsReference);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int elementsIndex = ModelHelper.IndexOfReference(this.Elements, element);
            if ((elementsIndex != -1))
            {
                return ModelHelper.CreatePath("elements", elementsIndex);
            }
            int arcsIndex = ModelHelper.IndexOfReference(this.Arcs, element);
            if ((arcsIndex != -1))
            {
                return ModelHelper.CreatePath("arcs", arcsIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "ELEMENTS"))
            {
                if ((index < this.Elements.Count))
                {
                    return this.Elements[index];
                }
                else
                {
                    return null;
                }
            }
            if ((reference == "ARCS"))
            {
                if ((index < this.Arcs.Count))
                {
                    return this.Arcs[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "ELEMENTS"))
            {
                return this._elements;
            }
            if ((feature == "ARCS"))
            {
                return this._arcs;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this._elements))
            {
                return "elements";
            }
            if ((container == this._arcs))
            {
                return "arcs";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://petrinet/1.0#//PetriNet")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the PetriNet class
        /// </summary>
        public class PetriNetChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private PetriNet _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public PetriNetChildrenCollection(PetriNet parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Elements.Count);
                    count = (count + this._parent.Arcs.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Elements.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Arcs.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Elements.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Arcs.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IElement elementsCasted = item.As<IElement>();
                if ((elementsCasted != null))
                {
                    this._parent.Elements.Add(elementsCasted);
                }
                IArc arcsCasted = item.As<IArc>();
                if ((arcsCasted != null))
                {
                    this._parent.Arcs.Add(arcsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Elements.Clear();
                this._parent.Arcs.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Elements.Contains(item))
                {
                    return true;
                }
                if (this._parent.Arcs.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> elementsEnumerator = this._parent.Elements.GetEnumerator();
                try
                {
                    for (
                    ; elementsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = elementsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    elementsEnumerator.Dispose();
                }
                IEnumerator<IModelElement> arcsEnumerator = this._parent.Arcs.GetEnumerator();
                try
                {
                    for (
                    ; arcsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = arcsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    arcsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IElement elementItem = item.As<IElement>();
                if (((elementItem != null) 
                            && this._parent.Elements.Remove(elementItem)))
                {
                    return true;
                }
                IArc arcItem = item.As<IArc>();
                if (((arcItem != null) 
                            && this._parent.Arcs.Remove(arcItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Elements).Concat(this._parent.Arcs).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the PetriNet class
        /// </summary>
        public class PetriNetReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private PetriNet _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public PetriNetReferencedElementsCollection(PetriNet parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Elements.Count);
                    count = (count + this._parent.Arcs.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Elements.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Arcs.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Elements.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Arcs.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IElement elementsCasted = item.As<IElement>();
                if ((elementsCasted != null))
                {
                    this._parent.Elements.Add(elementsCasted);
                }
                IArc arcsCasted = item.As<IArc>();
                if ((arcsCasted != null))
                {
                    this._parent.Arcs.Add(arcsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Elements.Clear();
                this._parent.Arcs.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Elements.Contains(item))
                {
                    return true;
                }
                if (this._parent.Arcs.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> elementsEnumerator = this._parent.Elements.GetEnumerator();
                try
                {
                    for (
                    ; elementsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = elementsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    elementsEnumerator.Dispose();
                }
                IEnumerator<IModelElement> arcsEnumerator = this._parent.Arcs.GetEnumerator();
                try
                {
                    for (
                    ; arcsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = arcsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    arcsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IElement elementItem = item.As<IElement>();
                if (((elementItem != null) 
                            && this._parent.Elements.Remove(elementItem)))
                {
                    return true;
                }
                IArc arcItem = item.As<IArc>();
                if (((arcItem != null) 
                            && this._parent.Arcs.Remove(arcItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Elements).Concat(this._parent.Arcs).GetEnumerator();
            }
        }
    }
}

